version: '3'
services:
  frontend:
    build:
      context: ./frontend # Path to your frontend app directory
      dockerfile: Dockerfile # Name of the Dockerfile for frontend
    ports:
      - 4200:4200 # Adjust the port as per your frontend app configuration
  backend:
    build:
      context: ./backend # Path to your backend app directory
      dockerfile: Dockerfile # Name of the Dockerfile for backend
    ports:
      - 3000:3000 # Adjust the port as per your backend app configuration
    depends_on:
      - mongodb
    environment:
      - MONGODB_URI="mongodb+srv://rohanrustagi21:2V0WpUvfuXMYn2yp@cluster0.7wtlhlq.mongodb.net/?retryWrites=true&w=majority"

 # Replace with your MongoDB connection URI
  mongodb:
    image: mongo
    ports:
      - 27017:27017 # Adjust the port as per your MongoDB configuration
    volumes:
      - ./data:/data/db # Path to persist MongoDB data
